# Generated by Django 4.2.6 on 2024-03-05 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_emailconfirmation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailConfirmation',
        ),
    ]
